### DISCUSSION TITLE
Playground endpoints settings doesn't work as expected

### DISCUSSION THREAD

**Discussion by aoudiamoncef** [graphql-java-kickstart/graphql-spring-boot#429] [Q&A]
**Describe the bug**
Playground endpoints settings doesn't work as expected, can't override default values.  
**To Reproduce**
```yaml
  playground:
    mapping: /test/playground

    endpoint:
      graphql:  /custom/test/graphql
      subscriptions: /custom/test/subscriptions
    static:
      basePath: /static
    cdn:
      enabled: false/true 
      version: latest
```

**Expected behavior**
endpoints settings works as expected.
**Screenshots**
![bug](https://user-images.githubusercontent.com/22281426/85394356-bf502a80-b54e-11ea-8029-30cc335f7798.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome(Version 83.0.4103.106 (Official Build) (64-bit))
- Spring Boot: 2.3.1
 - Starter: 7.0.1

**Additional context**

**Comment by BlasiusSecundus** [comment]
The actual properties are:

```properties
graphql.playground.endpoint=/test/custom/graphql
graphql.playground.subscriptionEndpoint=/test/custom/subscriptions
```

**Comment by BlasiusSecundus** [comment]
Also, for custom static base path, this should be the correct property:
```properties
graphql.playground.staticPath.base=/custom-static-path
```

**Comment by BlasiusSecundus** [comment]
Nevertheless, I found a typo in the documentation :)

**Comment by aoudiamoncef** [comment]
Hi @BlasiusSecundus,

 I have the parent yml block ```graphql``` in my configuration. 

I looked at the documentation and the source code oh this starter. I worked on Altair starter and I haven't any issue like this.

**Comment by BlasiusSecundus** [comment]
Note that the Playground starter uses slightly different properties than Altair / GraphiQL.

**Comment by BlasiusSecundus** [comment]
E. g. for GraphiQL / Altair, the property for custom GraphQL endpoint is indeed `endpoint.graphql`, but Playground uses simply `endpoint`.

**Comment by aoudiamoncef** [comment]
I used the right properties as it was expected in the documentation. If you have a small projet, let's add playground starter and you'll see if it's a bug or not. May be I missed something.

**Comment by BlasiusSecundus** [comment]
This should work:  
```yaml
graphql:
  playground:
    endpoint: /custom/test/graphql
    subscriptionEndpoint: /custom/test/subscriptions
```

**Comment by ghost** [comment]
Hi,

I've been facing issues getting subscriptions to work in my GraphQL Playground as well. I have tried the latest yml settings above ^, but I still get the same error of 

```
{
  "error": "Could not connect to websocket endpoint ws://localhost:8080/graphql. Please check if the endpoint url is correct."
}
```

May I know if there is some way to override the settings in Playground?

Additionally, when I try the websocket url (`ws://.....`) I'm getting a `Server cannot be reached` error. This is true even if I get the endpoint to the default `/graphql` or the a/m `/subscriptions`.

Been wondering for quite a while if websockets need to be manually implemented in Springboot, but if I understand correctly they do not.

Thank you!

P.S. I'm referencing the `example-graphql-subscriptions` example.

**Comment by BlasiusSecundus** [comment]
As for `example-graphql-subscriptions`, the following config should work:

```yaml
graphql:
  servlet:
    mapping: /custom-graphql-endpoint
    subscriptions:
      websocket:
        path: /custom-subscriptions-endpoint
  playground:
    endpoint: /custom-graphql-endpoint
    subscriptionEndpoint: /custom-subscriptions-endpoint
```
