### DISCUSSION TITLE
CORS enable not sending Access-Control-Allow-Origin in response

### DISCUSSION THREAD

**Discussion by javaspace007** [graphql-java-kickstart/graphql-spring-boot#684] [Q&A]
I am keep getting below error from UI.

**has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

 

my config in application properties file.

```
graphql:
  servlet:
    enabled: true
    actuator-metrics: true
    tracingEnabled: true
    cors-enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET, HEAD, POST, OPTIONS
```

 

using below dependancy

```
<dependency>
                <groupId>com.graphql-java-kickstart</groupId>
                <artifactId>graphql-spring-boot-starter</artifactId>
                <version>11.1.0</version>
</dependency>
```

 

Someone please help me here.
