### DISCUSSION TITLE
voyager can not load while max query depth sets

### DISCUSSION THREAD

**Discussion by SongHayoung** [graphql-java-kickstart/graphql-spring-boot#691] [Q&A] [answered]
I got some issues on using voyager and playground.
when i set `servlet.max-query-depth` voyager can not load page

Is there any problems on my properties?

```yml
graphql:
  servlet:
    max-query-depth: 4
```

![스크린샷 2021-07-25 00 35 14](https://user-images.githubusercontent.com/37806785/126873506-febb87d6-83e3-4b93-8e87-5835e86707a4.png)
