### ISSUE TITLE
Failed to load subscription client when CDN is enabled

### ISSUE THREAD

**Issue by sr1977** [graphql-java-kickstart/graphql-spring-boot#463]
When I configure CDN to be enabled, with a subscription endpoint specified - I'm getting a 404 error with the loading of `subscriptions-transport-ws-browser-client.js` - it appears to be defaulting to being served locally, which I think is down to this: 

https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/fe6d8c02f88388dea75f86a07dc230c3ac6e5f0b/graphiql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/graphiql/boot/GraphiQLController.java#L113-L114

The app is hosted in k8s, so I don't want to have to put in complex ingress rules for this. I have another app without a subscription and that works fine.

I am using graphiql-spring-boot-starter:7.1.0 and my application.yaml has:
```
graphiql:
  mapping: /graphiql
  cdn:
    enabled: true
    version: 0.17.5
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions 
```
