### ISSUE TITLE
Weird characters on Playground since last release

### ISSUE THREAD

**Issue by ooga** [graphql-java-kickstart/graphql-spring-boot#495]
**Describe the bug**
Weird characters on Playground since release `8.1.0`, looks like a charset issue.
Everything is working fine with version `8.0.0`

![image](https://user-images.githubusercontent.com/3911114/102908547-e8a73000-4477-11eb-98f3-a1accb9021f3.png)

**To Reproduce**
1. Use `com.graphql-java-kickstart:playground-spring-boot-starter:8.1.0`

**Comment by oliemansm** [comment]
Playground has been upgraded to 1.7.26 in release 8.1.0. Could you try with an earlier version of playground by enabling CDN to see if that "solves" the problem? That way we'll know if it's something in that release of Playground or if it's something else.

```yaml
graphql.playground:
    cdn:
        enabled: true
        version: "1.7.20"
```
