### ISSUE TITLE
CORS Feature in 8.1.1

### ISSUE THREAD

**Issue by PhilippS93** [graphql-java-kickstart/graphql-spring-boot#498]
**Describe the bug**
The CORS feature seems not to work, even when specifying wildcard operator. Seems like `org/springframework/web/cors/CorsConfiguration.java` is calling `getAllowedOrigins()` before the value is initialized by `setAllowedOrigins()`.

**Expected behavior**
CORS settings are are applied

**Comment by oliemansm** [comment]
@PhilippS93 So you've configured it like this?
```yaml
graphql.servlet.cors.allowed-origins: "*"
```

**Comment by PhilippS93** [comment]
Exactly, I tried (.yml file):

```
graphql:
  servlet:
    cors:
      allowed-origins:
        - "*"
        - "http://mydomain.com"
        - "http://mydomain.com:8080"
        - "^(http?://(?:.+\.)?mydomain\.com(?::\d{1,5})?)$."
```
This should have covered everything.

Best,
Philipp
