### ISSUE TITLE
/vendor/ files are not found

### ISSUE THREAD

**Issue by deeprobin** [graphql-java-kickstart/graphql-spring-boot#535]
**Describe the bug**
```
2021-02-18 17:26:27.124  WARN 6964 --- [nio-8080-exec-5] o.s.web.servlet.PageNotFound             : No mapping for GET /vendor/graphiql/es6-promise.auto.min.js
2021-02-18 17:26:27.129  WARN 6964 --- [nio-8080-exec-6] o.s.web.servlet.PageNotFound             : No mapping for GET /vendor/graphiql/fetch.min.js
2021-02-18 17:26:27.129  WARN 6964 --- [nio-8080-exec-7] o.s.web.servlet.PageNotFound             : No mapping for GET /vendor/graphiql/react.min.js
2021-02-18 17:26:27.130  WARN 6964 --- [nio-8080-exec-9] o.s.web.servlet.PageNotFound             : No mapping for GET /vendor/graphiql/react-dom.min.js
2021-02-18 17:26:27.130  WARN 6964 --- [io-8080-exec-10] o.s.web.servlet.PageNotFound             : No mapping for GET /vendor/graphiql/graphiql.min.css
2021-02-18 17:26:27.130  WARN 6964 --- [nio-8080-exec-8] o.s.web.servlet.PageNotFound             : No mapping for GET /vendor/graphiql/graphiql.min.js
2021-02-18 17:26:27.162  WARN 6964 --- [nio-8080-exec-1] o.s.web.servlet.PageNotFound             : No mapping for GET /vendor/graphiql/subscriptions-transport-ws-browser-client.js
2021-02-18 17:26:27.162  WARN 6964 --- [nio-8080-exec-2] o.s.web.servlet.PageNotFound             : No mapping for GET /vendor/graphiql/graphiql-subscriptions-fetcher-browser-client.js
```

**To Reproduce**
1. build.gradle.kts
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.4.1-SNAPSHOT"
	id("io.spring.dependency-management") version "1.0.10.RELEASE"
	`maven-publish`
	java
	kotlin("jvm") version "1.4.10"
	kotlin("plugin.serialization") version "1.4.10"
	kotlin("plugin.spring") version "1.4.10"
}

group = "de.motionmc"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8


val githubUsername = (project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")) as String
val githubPassword = (project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")) as String

repositories {
	mavenCentral()
	maven { url = uri("https://repo.spring.io/milestone") }
	maven { url = uri("https://repo.spring.io/snapshot") }
	maven { url = uri("https://oss.jfrog.org/artifactory/oss-snapshot-local") }
	maven("https://dl.bintray.com/kotlin/exposed")
	maven {
		name = "GitHubPackages"
		url = uri("https://maven.pkg.github.com/motionmc/core/")
		credentials {
			username = project.findProperty("gpr.user") as String? ?: System.getenv("GITHUB_ACTOR")
			password = project.findProperty("gpr.key") as String? ?: System.getenv("GITHUB_TOKEN")
		}
	}
}

dependencies {
	// Spring boot dependencies
	implementation("org.springframework.boot:spring-boot-starter")
	developmentOnly("org.springframework.boot:spring-boot-devtools")
	implementation("org.springframework.boot:spring-boot-starter-web")
	//implementation("com.graphql-java:graphql-spring-boot-starter:5.0.2")
	//implementation("com.graphql-java:graphql-java-spring-boot-starter-webmvc:2.0")
	//implementation("com.graphql-java:graphql-java-spring-boot-starter-webflux:2.0")
	implementation("com.graphql-java-kickstart:graphql-spring-boot-starter:11.0.0")
	runtimeOnly("com.graphql-java-kickstart:altair-spring-boot-starter:11.0.0")
	runtimeOnly("com.graphql-java-kickstart:graphiql-spring-boot-starter:11.0.0")
	runtimeOnly("com.graphql-java-kickstart:voyager-spring-boot-starter:11.0.0")
	implementation("org.springframework.boot:spring-boot-starter-security")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	implementation("io.springfox:springfox-boot-starter:3.0.0")

	// MotionMC dependencies
	implementation("de.motionmc:core:0.1.15-SNAPSHOT")

	// Other dependencies
	implementation("com.graphql-java:graphql-java:11.0")
	implementation("com.graphql-java:graphql-java-tools:5.2.4")
	implementation("com.google.guava:guava:26.0-jre")

	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.exposed:exposed-core:0.28.1")
	implementation("org.jetbrains.exposed:exposed-java-time:0.28.1")
	implementation("org.jetbrains.exposed:exposed-jdbc:0.28.1")
	implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.0.1")
	implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1")
}

tasks.withType<Test> {
	useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "1.8"
	}
}
```

application.yml
```yml
spring:
  application:
    name: graphql-todo-app
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    actuator-metrics: true
  playground:
    cdn:
      version: latest
altair:
  enabled: true
  cdn:
    enabled: false
graphiql:
  enabled: true
  cdn:
    enabled: false
    version: 0.17.5
  headers:
    Test: TestHeader
  props:
    variables:
      headerEditorEnabled: true
      headers: '{ "Authorization": "SomeValue" }'
voyager:
  enabled: true
  cdn:
    enabled: false
graphql.playground:
  enabled: true
  cdn:
    enabled: false
```

schema.graphqls
```graphql
type Query {
    userById(id: ID!): User
}

type User {
    id: ID,
    coins: Int,
    level: Int,
    experience: Int,
    createdAt: String
}
```

**Expected behavior**
That /vendor/ files are not served as 404
