### ISSUE TITLE
graphiql config headers do not work in new release 12.0.0

### ISSUE THREAD

**Issue by aihua5** [graphql-java-kickstart/graphql-spring-boot#726]
I upgraded the starter from 11.1.0 to 12.0.0.

Before I upgrade, I config the graphiql in application.yml 

`graphiql:           
  mapping: /
  headers:
    test: test`

When I post one graphql query, I can see we have one added header test:test

But after I upgrade to 12.0.0, I config the graphiql as below per new format

`graphql:
  graphiql:
    enabled: true
    mapping: /
    headers:
      test: test`

I expect I can see the added header but not.

Is there one bug for the graphiql config in appliation.yml?
Can anyone help to take a look? thanks.

**Comment by BlasiusSecundus** [comment]
A fix is in progress. Meanwhile, you can setup headers in the old fashioned way (before the starter reorganization):

```yaml
graphiql:
  headers:
    myHeader: myHeaderValue
  props:
    variables:
      headerEditorEnabled: true
```
