### ISSUE TITLE
Getting 404 for /graphiql or /graphql calls when upgrading Spring Boot 3.0.0

### ISSUE THREAD

**Issue by williamwjs** [graphql-java-kickstart/graphql-spring-boot#895]
**Describe the bug**
Getting 404 for /graphiql or /graphql calls when upgrading Spring Boot 3.0.0

**To Reproduce**

Bump Spring Boot to 3.0.0

**Expected behavior**
/graphiql could load or /graphql call could succeed

**Additional context**
My application.yml:

```
graphql:
  graphiql:
    enabled: true
    subscriptions:
      timeout: 30000
```
